import { PlatformConfig, PlatformId } from '../types';

export const PLATFORMS: Record<PlatformId, PlatformConfig> = {
  youtube: {
    id: 'youtube',
    name: 'YouTube',
    badge: 'Video & Shorts',
    iconName: 'Youtube',
    tagline: 'Download 4K / 1080p Videos, Shorts & MP3 Audio',
    placeholder: 'Paste YouTube video or shorts link (e.g., https://youtube.com/watch?v=... or /shorts/...)',
    sampleUrls: [
      'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
      'https://www.youtube.com/shorts/3i_bH1s_ZxE',
    ],
    theme: {
      name: 'YouTube Crimson',
      primaryHex: '#FF0000',
      gradient: 'from-red-600 via-rose-600 to-red-800',
      badgeBg: 'bg-red-500/20 text-red-400 border border-red-500/30',
      badgeText: 'text-red-400',
      borderAccent: 'border-red-500/40 focus-within:border-red-500',
      glow: 'shadow-[0_0_35px_-8px_rgba(239,68,68,0.35)]',
      buttonBg: 'bg-red-600 hover:bg-red-500 text-white shadow-lg shadow-red-600/30',
      buttonHover: 'hover:bg-red-500',
      cardBg: 'bg-stone-950/80 border-red-950/60',
      activeTab: 'bg-red-600 text-white shadow-md shadow-red-600/40',
    },
    supportedTypes: ['video', 'shorts', 'audio', 'image'],
  },
  instagram: {
    id: 'instagram',
    name: 'Instagram',
    badge: 'Reels & Stories',
    iconName: 'Instagram',
    tagline: 'Download Reels, Posts, Carousels, Stories & Audio',
    placeholder: 'Paste Instagram Reel or Post link (e.g., https://instagram.com/reel/... or /p/...)',
    sampleUrls: [
      'https://www.instagram.com/reel/C8qA19_xLkM/',
      'https://www.instagram.com/p/C6_kZ92L_mQ/',
    ],
    theme: {
      name: 'Instagram Sunset',
      primaryHex: '#E1306C',
      gradient: 'from-amber-500 via-rose-500 to-purple-600',
      badgeBg: 'bg-pink-500/20 text-pink-300 border border-pink-500/30',
      badgeText: 'text-pink-400',
      borderAccent: 'border-pink-500/40 focus-within:border-pink-500',
      glow: 'shadow-[0_0_35px_-8px_rgba(225,48,108,0.35)]',
      buttonBg: 'bg-gradient-to-r from-amber-500 via-rose-600 to-purple-600 hover:opacity-95 text-white shadow-lg shadow-pink-600/30',
      buttonHover: 'hover:opacity-90',
      cardBg: 'bg-stone-950/80 border-purple-950/60',
      activeTab: 'bg-gradient-to-r from-amber-500 via-rose-600 to-purple-600 text-white shadow-md shadow-purple-600/40',
    },
    supportedTypes: ['video', 'shorts', 'audio', 'image'],
  },
  tiktok: {
    id: 'tiktok',
    name: 'TikTok',
    badge: 'No Watermark HD',
    iconName: 'Music2',
    tagline: 'Download TikTok Videos without Watermark & Original Audio',
    placeholder: 'Paste TikTok video link (e.g., https://www.tiktok.com/@user/video/...)',
    sampleUrls: [
      'https://www.tiktok.com/@creative_mind/video/732194819284',
      'https://vt.tiktok.com/ZS2B9k8Lm/',
    ],
    theme: {
      name: 'TikTok Cyber Neon',
      primaryHex: '#00F2FE',
      gradient: 'from-cyan-400 via-slate-900 to-pink-500',
      badgeBg: 'bg-cyan-500/20 text-cyan-300 border border-cyan-500/30',
      badgeText: 'text-cyan-400',
      borderAccent: 'border-cyan-500/40 focus-within:border-pink-500',
      glow: 'shadow-[0_0_35px_-8px_rgba(0,242,254,0.35)]',
      buttonBg: 'bg-gradient-to-r from-cyan-500 to-pink-500 hover:from-cyan-400 hover:to-pink-400 text-slate-950 font-semibold shadow-lg shadow-cyan-500/25',
      buttonHover: 'hover:opacity-95',
      cardBg: 'bg-zinc-950/85 border-cyan-950/60',
      activeTab: 'bg-gradient-to-r from-cyan-500 to-pink-500 text-slate-950 font-bold shadow-md shadow-cyan-500/30',
    },
    supportedTypes: ['video', 'shorts', 'audio', 'image'],
  },
  facebook: {
    id: 'facebook',
    name: 'Facebook',
    badge: 'Watch & Reels',
    iconName: 'Facebook',
    tagline: 'Download Facebook Reels, Watch Shows & Full HD Videos',
    placeholder: 'Paste Facebook video or reel link (e.g., https://facebook.com/watch/... or /reel/...)',
    sampleUrls: [
      'https://www.facebook.com/reel/104928172948271/',
      'https://fb.watch/vN7zK91s_q/',
    ],
    theme: {
      name: 'Meta Classic Blue',
      primaryHex: '#1877F2',
      gradient: 'from-blue-600 via-indigo-600 to-blue-800',
      badgeBg: 'bg-blue-500/20 text-blue-300 border border-blue-500/30',
      badgeText: 'text-blue-400',
      borderAccent: 'border-blue-500/40 focus-within:border-blue-500',
      glow: 'shadow-[0_0_35px_-8px_rgba(24,119,242,0.35)]',
      buttonBg: 'bg-blue-600 hover:bg-blue-500 text-white shadow-lg shadow-blue-600/30',
      buttonHover: 'hover:bg-blue-500',
      cardBg: 'bg-slate-950/80 border-blue-950/60',
      activeTab: 'bg-blue-600 text-white shadow-md shadow-blue-600/40',
    },
    supportedTypes: ['video', 'shorts', 'audio'],
  },
  linkedin: {
    id: 'linkedin',
    name: 'LinkedIn',
    badge: 'Videos & Slides',
    iconName: 'Linkedin',
    tagline: 'Download Professional Videos, Presentations, Documents & Infographics',
    placeholder: 'Paste LinkedIn post link containing video or slides (e.g., https://linkedin.com/posts/...)',
    sampleUrls: [
      'https://www.linkedin.com/posts/tech-innovation-presentation_activity-71829384910239/',
    ],
    theme: {
      name: 'LinkedIn Azure',
      primaryHex: '#0A66C2',
      gradient: 'from-sky-600 via-blue-700 to-indigo-800',
      badgeBg: 'bg-sky-500/20 text-sky-300 border border-sky-500/30',
      badgeText: 'text-sky-400',
      borderAccent: 'border-sky-500/40 focus-within:border-sky-500',
      glow: 'shadow-[0_0_35px_-8px_rgba(10,102,194,0.35)]',
      buttonBg: 'bg-sky-600 hover:bg-sky-500 text-white shadow-lg shadow-sky-600/30',
      buttonHover: 'hover:bg-sky-500',
      cardBg: 'bg-slate-950/80 border-sky-950/60',
      activeTab: 'bg-sky-600 text-white shadow-md shadow-sky-600/40',
    },
    supportedTypes: ['video', 'file', 'image'],
  },
  threads: {
    id: 'threads',
    name: 'Threads',
    badge: 'Media & Clips',
    iconName: 'AtSign',
    tagline: 'Download Threads Videos, Voice Notes & High-Res Images',
    placeholder: 'Paste Threads post link (e.g., https://www.threads.net/@user/post/...)',
    sampleUrls: [
      'https://www.threads.net/@photographer_daily/post/C79qLz1xP8Q',
    ],
    theme: {
      name: 'Threads Monochrome',
      primaryHex: '#FFFFFF',
      gradient: 'from-neutral-200 via-neutral-400 to-neutral-100',
      badgeBg: 'bg-white/10 text-white border border-white/20',
      badgeText: 'text-white',
      borderAccent: 'border-white/30 focus-within:border-white',
      glow: 'shadow-[0_0_35px_-8px_rgba(255,255,255,0.25)]',
      buttonBg: 'bg-white text-neutral-950 hover:bg-neutral-200 font-semibold shadow-lg shadow-white/10',
      buttonHover: 'hover:bg-neutral-200',
      cardBg: 'bg-neutral-950/85 border-neutral-800/80',
      activeTab: 'bg-white text-neutral-950 font-semibold shadow-md',
    },
    supportedTypes: ['video', 'image', 'audio'],
  },
  twitter: {
    id: 'twitter',
    name: 'X (Twitter)',
    badge: 'Clips & GIFs',
    iconName: 'Twitter',
    tagline: 'Download X/Twitter HD Videos, Spaces Audio & GIFs',
    placeholder: 'Paste X / Twitter post link (e.g., https://x.com/user/status/...)',
    sampleUrls: [
      'https://x.com/nasa/status/179283749281749',
    ],
    theme: {
      name: 'X Slate',
      primaryHex: '#38BDF8',
      gradient: 'from-sky-500 via-blue-600 to-slate-900',
      badgeBg: 'bg-sky-500/20 text-sky-300 border border-sky-500/30',
      badgeText: 'text-sky-400',
      borderAccent: 'border-sky-500/40 focus-within:border-sky-500',
      glow: 'shadow-[0_0_35px_-8px_rgba(56,189,248,0.35)]',
      buttonBg: 'bg-sky-500 hover:bg-sky-400 text-slate-950 font-semibold shadow-lg shadow-sky-500/25',
      buttonHover: 'hover:bg-sky-400',
      cardBg: 'bg-slate-950/80 border-slate-800',
      activeTab: 'bg-sky-500 text-slate-950 font-semibold shadow-md',
    },
    supportedTypes: ['video', 'audio', 'image'],
  },
  direct: {
    id: 'direct',
    name: 'Turbo Heavy Files',
    badge: '16x Multi-Threaded',
    iconName: 'Zap',
    tagline: 'Multi-threaded chunked downloader for ISO, ZIP, 4K Raw, APK & Large Files',
    placeholder: 'Enter direct heavy file URL (e.g., https://example.com/archive.zip, ubuntu.iso, etc.)',
    sampleUrls: [
      'https://releases.ubuntu.com/24.04/ubuntu-24.04-desktop-amd64.iso',
      'https://sample-videos.com/video321/mp4/1080/big_buck_bunny_1080p_10mb.mp4',
    ],
    theme: {
      name: 'Turbo Speed Emerald',
      primaryHex: '#10B981',
      gradient: 'from-emerald-500 via-teal-600 to-cyan-700',
      badgeBg: 'bg-emerald-500/20 text-emerald-300 border border-emerald-500/30',
      badgeText: 'text-emerald-400',
      borderAccent: 'border-emerald-500/40 focus-within:border-emerald-500',
      glow: 'shadow-[0_0_35px_-8px_rgba(16,185,129,0.35)]',
      buttonBg: 'bg-gradient-to-r from-emerald-500 to-teal-600 hover:from-emerald-400 hover:to-teal-500 text-slate-950 font-bold shadow-lg shadow-emerald-500/30',
      buttonHover: 'hover:opacity-90',
      cardBg: 'bg-slate-950/85 border-emerald-950/60',
      activeTab: 'bg-gradient-to-r from-emerald-500 to-teal-600 text-slate-950 font-bold shadow-md shadow-emerald-500/30',
    },
    supportedTypes: ['file', 'video'],
  },
};
